config/routes.rb
Rails.application.routes.draw do
  get 'welcome/:id', to: 'welcome#users'
  get '/contact', to: 'contact#contact'
  get '/team', to: 'equipe#team'
  get '/', to: 'accueil#home', as: 'home'
  resources :gossips
  resources :users, only: [:show, :new, :create]
  resources :city, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, length: { in: 3..14 }
	validates :content, presence: true
	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
end

app/models/gossip_tag_table.rb
class GossipTagTable < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates:content, presence: true
	belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates:title, length: {in:3..14}
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def home
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController

def show 
    @city = City.find(params[:id])
end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/equipe_controller.rb
class EquipeController < ApplicationController
  def team
  end
end

app/controllers/potin_controller.rb
class PotinController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params.require(:user).permit(:email, :password, :first_name))
  	city = City.new
  	@user.city = city
  	if @user.save
  		redirect_to new_session_path
  	else
  		render 'new'
  	end
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/equipe_helper.rb
module EquipeHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/potin_helper.rb
module PotinHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=home_path%>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="<%=gossips_path%>">Gossips</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=team_path%>">Equipe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=contact_path%>">Contact</a>
      </li>
    </ul>
  </div>
</nav>


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">S'inscrire</h1>
</div>

<p>
  <%= form_for(@user) do |f| %>
<div class="form-group">
  <label>Email : </label>
  <%= f.text_field :email, class: 'form-control'%>
</div>
<div class="form-group">
  <label>Mot de passe : </label>
  <%= f.text_field :password, class: 'form-control'%>
</div>
<div class="form-group">
  <label>Prénom : </label>
  <%= f.text_field :first_name, class: 'form-control'%>
</div>
<div class="form-group">
  <button type="submit" class="btn btn-primary">Valider</button>
</div>
<% end %>
</p>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=home_path%>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="<%=gossips_path%>">Gossips</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=team_path%>">Equipe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=contact_path%>">Contact</a>
      </li>
    </ul>
  </div>
</nav>

<div class="jumbotron text-center">
<h3><%= @user.first_name%> <%= @user.last_name%></h3>
<p>Description : <%= @user.description %></p>
<p>Email : <%= @user.email %></p>
<p>Age : <%= @user.age %> ans </p>
<p>City : <a href="<%= city_path(@user.city.id) %>"><%= @user.city.name %></a></p>
</div>